#- name: "install lamp stack"
#    apt:
#      name: ['apache2', 'mysql-server', 'php7.0', 'php7.0-mysql']
#      state: latest
#      update_cache: yes
#  tags: setup_server

- name: "install lamp stack"
  apt:
    name: ['apache2', 'mysql-server', 'php7.0', 'php7.0-mysql']
    state: latest
  tags: setup_server

- name: "start services"
  service:
    name: {{ item }}
      state: started
      enabled: yes
      sudo: yes
    with_items:
      - apache2
      - mysql

