- name: "SSH public key for root access of 'pi' user with state 'present'"
  authorized_key:
    user: "pi"
    state: "present"
    key: "{{ lookup('file', '~/.ssh/homeserver.id_rsa.pub') }}"
  tags: copy_key

